language: r
cache: packages

r:
  - release
  - bioc-release

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - magrittr 
  - ape
  - phangorn
  - phytools 
  - caper 
  - scatterplot3d 
  - biglm 
  - testthat

bioc_packages:
  - Biostrings

script:
  - Rscript -e "library(testthat); test_package('phylofactor')"

notifications:
  email:
    on_success: change
    on_failure: always
