language: r
cache: packages

sudo: false

r:
  - release
  - bioc-release

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - magrittr 
  - ape
  - phangorn
  - phytools 
  - caper 
  - scatterplot3d 
  - biglm 
  - testthat
  - devtools

bioc_packages:
  - Biostrings
  - ggtree

script:
  - Rscript -e "devtools::install_github('reptalex/phylofactor',INSTALL_opts = "--install-tests")"
  - Rscript -e "library(testthat); test_package('phylofactor')"

notifications:
  email:
    on_success: change
    on_failure: always
