language: r
cache: packages

r:
  - release
  - devel
  - bioc-release

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - magrittr 
  - ape
  - phangorn
  - phytools 
  - caper 
  - scatterplot3d 
  - biglm 
  - testthat

script:
  - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite('Biostrings')"
  - Rscript -e "devtools::install_github('reptalex/phylofactor'); library(testthat); test_package('phylofactor')"

notifications:
  email:
    on_success: change
    on_failure: always
